version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    command: sh -c "python init_db.py && python run.py"
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge